from .calculatortest import *
from .timeconvertertest import *
from .chargeconfigtest import *
from .postcodetest import *
from .time_segments_test import *
from .chargeconfigtest import *
from .calculator_form_test import *
from .energy_cal_test import * 
from .weather_data_api_test import * 
from .calculatorpresentationtest import *